const Sdata = [
  {
    id: 1,
    title: "Gardens",
    image: "/images/pop1.jpg",
    desc: "Welcome to Eziana Palm Hotel, a luxurious  retreat nestled amidst enchanting gardens. Our hotel offers a tranquil haven for discerning travelers seeking both relaxation and sophistication. Immerse yourself in the serene ambiance as you unwind in our meticulously designed rooms, adorned with elegant furnishings and modern amenities. Indulge in the culinary delights of our exquisite restaurant, where our talented chefs create delectable dishes inspired by local and international flavors. Explore our meticulously landscaped gardens, a verdant oasis that invites you to stroll, unwind, and connect with nature. Whether you're seeking a peaceful getaway or a stylish venue for your event, Eziana Palm Hotel promises an unforgettable experience where comfort, elegance, and personalized service harmoniously blend.Discover the epitome of luxury at Eziana Palm Hotel, a prestigious four-star establishment renowned for its impeccable service and refined elegance. Set against a backdrop of lush gardens, our hotel exudes a captivating charm that enchants guests from the moment they arrive.Step into our opulent lobby, where the warm ambiance and attentive staff immediately make you feel at home. The tastefully appointed rooms and suites provide a sanctuary of comfort, featuring plush bedding, modern amenities, and breathtaking views of the meticulously manicured gardens.",
    sidepara: "At Eziana Palm Hotel, we redefine luxury with our unwavering dedication to providing an extraordinary stay. Immerse yourself in a world of sophistication, tranquility, and unparalleled hospitality, where every moment is crafted to perfection.",
    paraImage_one: "/images/singlepage/single-1.jpg",
    paraImage_two: "/images/singlepage/single-2.jpg",
  },
  {
    id: 2,
    title: "Restaurant",
    image: "/images/pop2.jpg",
    desc: "Welcome to Eziana Restaurant, a culinary haven where flavors from around the world come together in a harmonious symphony of taste. Our restaurant is known for its exquisite blend of both continental and local cuisine, offering a diverse menu that caters to every palate.Indulge in a culinary journey as our talented chefs skillfully craft delectable dishes inspired by international flavors. From mouthwatering European classics to Asian delicacies, our continental menu promises a gastronomic experience that will tantalize your taste buds. Immerse yourself in a world of flavors, where each dish is meticulously prepared using the finest ingredients, ensuring a dining experience that is both memorable and satisfying.For those seeking an authentic taste of the local cuisine, our menu showcases a variety of dishes that highlight the vibrant flavors and culinary traditions of the region. From aromatic spices to fresh seafood and local produce, our local menu celebrates the rich cultural heritage of our location. Sample traditional dishes that capture the essence of the local cuisine, offering a delightful fusion of flavors and textures that will transport you to the heart of the destination.",
    sidepara: "Step into the captivating ambiance of Eziana Restaurant, where every detail has been carefully curated to provide an extraordinary dining experience.",
    paraImage_one: "/images/singlepage/single-1.jpg",
    paraImage_two: "/images/singlepage/single-2.jpg",
  },
  {
    id: 3,
    title: "Rooms",
    image: "/images/pop6.jpg",
    desc: "At Eziana Palm Hotel, we offer a range of meticulously designed rooms to suit the preferences and needs of our guests. Whether you choose our Executive, Twin Beds, or Deluxe Bed rooms, each one is thoughtfully crafted to provide comfort, relaxation, and a delightful stay.Our Executive rooms embody elegance and sophistication, offering a spacious and luxurious retreat. From the moment you step inside, you'll be greeted by a harmonious blend of stylish décor and modern amenities. The Executive rooms provide a serene sanctuary where you can unwind and rejuvenate after a long day. Sink into the plush bedding, indulge in the tranquil ambiance, and take advantage of the amenities designed to enhance your comfort and convenience.For those traveling with a companion or seeking separate sleeping arrangements, our Twin Beds rooms offer the perfect solution. These rooms feature two comfortable beds, allowing you and your companion to enjoy a restful night's sleep in privacy and comfort. The Twin Beds rooms are designed with attention to detail, offering a cozy and inviting atmosphere where you can recharge and relax. If you desire the ultimate indulgence, our Deluxe Bed rooms provide a haven of serenity and refinement. These rooms are characterized by spaciousness, luxurious furnishings, and attention to detail. Experience a restful night's sleep on our deluxe beds, enveloped in high-quality linens and plush pillows. The Deluxe Bed rooms also feature additional amenities and thoughtful touches to ensure your stay is nothing short of exceptional.Regardless of the room type you choose, each one is equipped with modern amenities such as high-speed internet access, flat-screen TVs, minibars, and spacious en-suite bathrooms. Our rooms are meticulously maintained and cleaned to ensure a hygienic and comfortable environment for our guests.At Eziana Palm Hotel, we take pride in creating a welcoming and comfortable atmosphere in our rooms, allowing you to unwind and recharge in style. Whether you opt for the Executive, Twin Beds, or Deluxe Bed rooms, each one promises a memorable and enjoyable stay, ensuring your time with us is nothing short of extraordinary.",
    sidepara: "Our Executive rooms offer a lavish escape with spacious interiors, stylish decor, and modern amenities, providing a luxurious retreat for discerning travelers.The Twin Beds rooms provide the perfect arrangement for friends or family, allowing for comfortable and private sleeping arrangements while enjoying the convenience of our hotel's amenities.Indulge in the opulence of our Deluxe Bed rooms, where elegant furnishings, deluxe bedding, and thoughtful touches combine to create an exquisite haven of relaxation and refinement.",
    paraImage_one: "/images/singlepage/single-1.jpg",
    paraImage_two: "/images/singlepage/single-2.jpg",
  },
  {
    id: 4,
    title: "Television and DSTV",
    image: "/images/television.jpg",
    desc: "At Eziana Palm Hotel, we understand the importance of staying connected and keeping our guests updated with the latest information and entertainment. That's why we provide state-of-the-art televisions in all our rooms, accompanied by DSTV (Digital Satellite Television) to ensure a wide range of channels and programming options.Our room televisions are equipped with DSTV, offering a diverse selection of local and international channels. Whether you're interested in news, sports, movies, or your favorite TV shows, you'll have access to an extensive lineup of channels that cater to various interests and preferences.Stay informed with up-to-date news coverage from around the country and beyond, allowing you to stay abreast of current events and developments. Enjoy live sports broadcasts, including popular local and international matches, ensuring you never miss a thrilling game or match.For entertainment enthusiasts, indulge in your favorite programs and series, with a variety of channels offering an array of genres to suit all tastes. Whether you prefer dramas, comedies, documentaries, or reality shows, our DSTV service ensures a wide range of options to keep you entertained throughout your stay.At Eziana Palm Hotel, we strive to provide our guests with a comprehensive television and DSTV experience, allowing you to relax, unwind, and stay connected to the world. Enjoy your favorite programs, catch up on the latest news, and immerse yourself in a world of entertainment from the comfort of your room.",
    sidepara: "Our room televisions at Eziana Palm Hotel feature DSTV, providing a wide selection of local and international channels to keep you updated with news, sports, and entertainment from around the country and beyond.Stay informed and entertained with our state-of-the-art televisions and DSTV, offering a diverse range of programming options that cater to various interests and preferences.From live sports matches to your favorite TV shows, our television and DSTV service ensure that you can enjoy a variety of programs, keeping you engaged and entertained throughout your stay.",
    paraImage_one: "/images/singlepage/single-1.jpg",
    paraImage_two: "/images/singlepage/single-2.jpg",
  },
  {
    id: 5,
    title: "Conference Hall",
    image: "/images/conference.jpg",
    desc: "Welcome to our prestigious conference facilities at Eziana Palm Hotel, where business meets elegance and success is nurtured. Our conference venues are meticulously designed to provide the ideal setting for productive meetings, seminars, workshops, and corporate events.Step into our state-of-the-art conference rooms, featuring modern technology and flexible seating arrangements to accommodate varying group sizes. With ample natural light and stylish decor, our venues offer a professional yet inviting atmosphere that fosters creativity and collaboration.Our dedicated event staff is committed to ensuring the smooth execution of your conference. From setting up audiovisual equipment to providing personalized catering services, we strive to meet your every requirement. Our team will assist you every step of the way, ensuring a seamless and successful event.Whether you are hosting a small board meeting or a large-scale conference, our versatile spaces can be tailored to your specific needs. With advanced audiovisual capabilities, high-speed internet access, and comfortable seating, we provide the essential amenities to support a productive and engaging gathering.During breaks, attendees can enjoy refreshments and networking opportunities in our stylish pre-function areas, designed to encourage interactions and connections. Our professional staff is always on hand to provide attentive service, ensuring your conference runs smoothly and leaves a lasting impression on your guests.At Eziana Palm Hotel, we understand the importance of a successful conference, and we are dedicated to creating an exceptional experience for you and your attendees. Trust us to deliver a seamless event that combines functional facilities, impeccable service, and a touch of sophistication to elevate your conference to new heights.",
    sidepara: "Our conference facilities at Eziana Palm Hotel offer state-of-the-art venues with modern technology, flexible seating arrangements, and a professional atmosphere to host successful meetings and events.With attentive staff, advanced amenities, and stylish pre-function areas, our conference spaces are designed to facilitate productivity, networking, and seamless event execution. Experience a seamless and sophisticated conference experience at Eziana Palm Hotel, where our dedicated team ensures every detail is taken care of, allowing you to focus on delivering a memorable and successful event. ",
    paraImage_one: "/images/singlepage/single-1.jpg",
    paraImage_two: "/images/singlepage/single-2.jpg",
  },
    
  {
    id: 6,
    title: "Our Team",
    image: "/images/reception.jpg",
    desc: "At Eziana Palm Hotel, our team is the heart and soul of our exceptional hospitality. Comprising dedicated professionals who are passionate about providing the highest level of service, our team is committed to ensuring your stay is memorable and beyond expectations. From the moment you arrive, our warm and welcoming front desk staff will greet you with a genuine smile, ready to assist you with check-in, offer recommendations, and address any inquiries you may have. They are knowledgeable about the hotel's facilities, local attractions, and are always eager to make your stay as comfortable and enjoyable as possible.Behind the scenes, our housekeeping team works diligently to maintain impeccable cleanliness and create a refreshing atmosphere in your room. They pay attention to every detail to ensure your space is pristine, ensuring a comfortable and inviting environment throughout your stay.Our dedicated concierge team is available to curate personalized experiences, assist with transportation arrangements, and provide valuable insights into the local area. They are well-versed in the best restaurants, attractions, and activities, ensuring you make the most of your time during your visit. In our restaurant, our talented chefs and attentive waitstaff work together to create a culinary experience that delights the senses. They are passionate about delivering exceptional dishes and providing attentive service, ensuring each meal is a memorable and satisfying experience.At Eziana Palm Hotel, our team embodies the spirit of hospitality, combining professionalism, warmth, and a genuine desire to exceed your expectations. With their unwavering dedication and commitment to service excellence, our team is here to ensure your stay is nothing short of extraordinary.",
    sidepara: "Our team at Eziana Palm Hotel is a passionate group of professionals dedicated to providing exceptional service, ensuring your stay is memorable and enjoyable.From our friendly front desk staff to our attentive housekeeping and concierge team, we are committed to exceeding your expectations and making your experience seamless and delightful.With a team of talented chefs and attentive waitstaff in our restaurant, we strive to create a culinary journey that tantalizes the taste buds and leaves a lasting impression.",
    paraImage_one: "/images/singlepage/single-1.jpg",
    paraImage_two: "/images/singlepage/single-2.jpg",
  },
]

export default Sdata
